name: Download and Release Files

on:
  workflow_dispatch:
    inputs:
      headers:
        description: 'Headers'
        required: false
      url:
        description: 'URL'
        required: true
      task_name:
        description: 'Task Name'
        required: false
      file_name:
        description: 'File Name'
        required: false

jobs:
  download_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download files
        run: |
          echo "${{ inputs.url }}"
          echo "${{ inputs.headers }}"
          aria2c -x16 --header="${{ inputs.headers }}" -d /opt/dls ${{ inputs.url }}
          
      - name: Upload files ZIP to release
        env:
          SECRETS_VTOKEN: ${{ secrets.vtoken }}
          FILE_NAME: ${{ inputs.file_name }}
          TASK_NAME: ${{ inputs.task_name }}
        run: |
          python main.py
