name: test

on:
  workflow_dispatch:
    inputs:
      headers:
        description: 'Headers'
        required: false

jobs:
  download_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: hpy
        env:
          SECRETS_VTOKEN: ${{ secrets.vtoken }}
        run: |
          python main.py
